from typing import Optional, List
from ninja import Router, Schema
from django.utils.text import slugify

from inventory.models import Category

router = Router()

# Create schema for Category in
# ==========================================
# Schema: Category In
# ==========================================
class CategoryIn(Schema):
    name: str
    slug: str
    is_active: bool
    level: Optional[int] = 0
    parent_id: Optional[int] = None


# ==========================================
# Schema: Category Bulk In
# ==========================================
class CategoryBulkIn(Schema):
    name: str
    slug: str
    is_active: bool = True
    parent_id: Optional[int] = None



@router.post(
    "/category/create",
    tags=["module4"],
    summary="Create a New Category",
    description="Creates a new category with optional parent and slug, Slug is"
    "autogenerated if not provided.",
)
def create_category(request, data: CategoryIn):
    slug = data.slug or slugify(data.name)
    Category.objects.create(
        name=data.name,
        slug=slug,
        is_active=data.is_active,
        level=data.level,
        parent_id=data.parent_id,
    )
    return


@router.post(
    "/category/save",
    tags=["module4"],
    summary="Create a New Category with save() method",
)
def create_category_save(request, data: CategoryIn):
    category = Category(
        name=data.name,
        slug=data.slug,
        is_active=data.is_active,
        level = data.level,
        parent_id=data.parent_id,
    )
    category.save()
    # return {'id': category.id, 'message': 'Category saved successfully.'}
    return



@router.post(
    "/create/bulk",
    tags=["module4"],
    summary="Create multiple categories with bulk_create()",
)
def bulk_create_categories(request, data: List[CategoryBulkIn]):
    categories = [
        Category(
            name=item.name,
            slug=item.slug,
            is_active=item.is_active,
            parent_id=item.parent_id,
        ) for item in data
    ]
    Category.objects.bulk_create(categories)
    return
