from typing import Optional, List
from ninja import Router, Schema
from django.utils.text import slugify

from inventory.models import Category

router = Router()

# Create schema for Category in
# ==========================================
# Schema: Category In
# ==========================================
class CategoryIn(Schema):
    name: str
    slug: str
    is_active: bool
    level: Optional[int] = 0
    parent_id: Optional[int] = None


# ==========================================
# Schema: Category Bulk In
# ==========================================
class CategoryBulkIn(Schema):
    name: str
    slug: str
    is_active: bool = True
    parent_id: Optional[int] = None


# ==========================================
# Schema: Category Update In
# ==========================================
class CategoryUpdateIn(Schema):
    name: Optional[str] = None
    slug: Optional[str] = None
    is_active: Optional[bool] = None
    parent_id: Optional[int] = None



@router.post(
    "/category/create",
    tags=["module4"],
    summary="Create a New Category",
    description="Creates a new category with optional parent and slug, Slug is"
    "autogenerated if not provided.",
)
def create_category(request, data: CategoryIn):
    slug = data.slug or slugify(data.name)
    Category.objects.create(
        name=data.name,
        slug=slug,
        is_active=data.is_active,
        level=data.level,
        parent_id=data.parent_id,
    )
    return


@router.post(
    "/category/save",
    tags=["module4"],
    summary="Create a New Category with save() method",
)
def create_category_save(request, data: CategoryIn):
    category = Category(
        name=data.name,
        slug=data.slug,
        is_active=data.is_active,
        level = data.level,
        parent_id=data.parent_id,
    )
    category.save()
    # return {'id': category.id, 'message': 'Category saved successfully.'}
    return



@router.post(
    "/create/bulk",
    tags=["module4"],
    summary="Create multiple categories with bulk_create()",
)
def bulk_create_categories(request, data: List[CategoryBulkIn]):
    categories = [
        Category(
            name=item.name,
            slug=item.slug,
            is_active=item.is_active,
            parent_id=item.parent_id,
        ) for item in data
    ]
    Category.objects.bulk_create(categories)
    return



@router.put(
    '/category/update/full/{category_id}',
    tags=['module4'],
    summary='Update an existing category by ID (full update)'
)
def update_category(request, category_id: int, data: CategoryUpdateIn):
    try:
        category = Category.objects.get(id=category_id)
    except Category.DoesNotExist:
        return {"error": "Category not found."}

    if data.name is not None:
        category.name = data.name
    if data.slug is not None:
        category.slug = data.slug
    if data.is_active is not None:
        category.is_active = data.is_active
    if data.parent_id is not None:
        category.parent_id = data.parent_id

    category.save()
    return {'status': 'updated'}


@router.put(
    '/category/update/partial/{category_id}',
    tags=['module4'],
    summary='Update an existing category by ID (partial update)'
)
def partial_update_category(request, category_id: int, data: CategoryUpdateIn):
    try:
        category = Category.objects.get(id=category_id)
    except Category.DoesNotExist:
        return {'error': 'Category not found.'}

    udpated_fields = []

    if data.name is not None:
        category.name = data.name
        udpated_fields.append('name')
    if data.slug is not None:
            category.slug = data.slug
            udpated_fields.append('slug')
    if data.is_active is not None:
            category.is_active = data.is_active
            udpated_fields.append('is_active')
    if data.parent_id is not None:
            category.parent_id = data.parent_id
            udpated_fields.append('parent_id')

    if udpated_fields:
         category.save(update_fields=udpated_fields)

    return {'status': 'updated', 'fields_updated': udpated_fields}